### ISSUE TITLE
DoorDirection

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/Edgar-Unity#100]
Is there any way to get DoorDirection of a DoorInstance? 
I want to know which doors of a RoomInstance are entrances, or exits, but currently in DoorInstance there isn't any property to get direction.

Regards

**Comment by OndrejNepozitek** [comment]
Hello, this is currently not possible but I think it's a good suggestion for an improvement. As of now, this information is not even returned by Edgar-DotNet so the Unity asset has no way make it available. If you're interested, I should be able to implement this in a few days.

**Comment by pvalium** [comment]
It's necessary for me, because i want to set levers-buttons-traps, etc that
open/closes exit, for example.

I think is a interesting feature in order to have more control of rooms. If
you can do it, it will be awesome.

**Comment by OndrejNepozitek** [comment]
Hey,
please send me an email at ondra@nepozitek.cz so I can reply to you with a modified version of Edgar.
