### ISSUE TITLE
Some Code Error In The Doc

### ISSUE THREAD

**Issue by hyf4053** [OndrejNepozitek/Edgar-Unity#102]
I just found a very little problem in the document which is in the (PRO) Dead Cells, the [Input Setup Section](https://ondrejnepozitek.github.io/Edgar-Unity/docs/examples/dead-cells/#input-setup).
In "input setup task that prepares the level description" 
`levelDescription.AddCorridorConnection(connection, RoomTemplates.CorridorRoomTemplates.ToList(), corridorRoom);`
It should be 
`levelDescription.AddCorridorConnection(connection, corridorRoom,RoomTemplates.CorridorRoomTemplates.ToList());`

**Comment by OndrejNepozitek** [comment]
Thank you! I'll fix that.
