### ISSUE TITLE
Prefabs Disconnecting

### ISSUE THREAD

**Issue by djaydino** [OndrejNepozitek/Edgar-Unity#105]
Hi.
I just noticed a big issue for the generator, we use prefabs inside the rooms, but when generated they are no longer prefabs. on version : 2.0.0-alpha.8-hotfix.0

**Comment by OndrejNepozitek** [comment]
This is now described here: https://ondrejnepozitek.github.io/Edgar-Unity/docs/recipes/prefabs-in-editor/
