### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/Edgar-Unity#109]
I had thought if it would be possible for the people who have bought the pro version, to give us a coupon to redeem it in the unity asset store. In this way, we can help you with positive feedback, and we also benefit from having it integrated into unity.
Regards

**Comment by OndrejNepozitek** [comment]
Hello, I'd love to give everyone with the PRO version a coupon for the Asset Store but Unity only provides 12 such coupons per asset per year. So, there's, unfortunately, no simple way to make everyone happy.

**Comment by pvalium** [comment]
Well, 12 positive reviews per year, it's better than nothing xD

Good job dude

**Comment by OndrejNepozitek** [comment]
I cannot promise anything but I might do a raffle and give away some of the coupons for people who already own the asset on itch.

**Comment by OndrejNepozitek** [comment]
Hello, I'm doing a giveaway on itch right now! You can find more information here: https://ondrejnepozitek.itch.io/edgar-pro/devlog/354649/asset-store-giveaway-for-itchio-owners

Feel free to participate
