### ISSUE TITLE
Question about doors

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/Edgar-Unity#111]
I want to know if is posible that doors have height > 1. Ie, if I use a tileset like this:
![image](https://user-images.githubusercontent.com/20306610/163673145-a06b6754-1b69-4437-ab22-f1b6adcd8de6.png)
I have vertical and bottom walls of 1 tile, but top wall is 2 tiles.
If I put a door, when dungeon generates only top tile is removed:
![image](https://user-images.githubusercontent.com/20306610/163673223-d8900a49-1d3e-44e2-a4ae-13d810c3ea46.png)

Is this possible?

Regards

**Comment by OndrejNepozitek** [comment]
Sure, it's possible. Please take a look here:
https://ondrejnepozitek.github.io/Edgar-Unity/docs/other/faq/#how-to-deal-with-wider-walls

**Comment by pvalium** [comment]
works like a charm.

Thank you!
