### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by ecarpintero** [OndrejNepozitek/Edgar-Unity#113]
Buenas.

The generator was not able to produce a level within a given time limit. The reason for that is usually that there is some problem with the configuration of the generator.

He probado a cambiar la configuracion del Dunegeon Generator.
Las puertas tanto en el pasillo como la habitacion es de 1 de tamaño. El pasillo tiene 2 puertas y la habitacion 4. Estan puestas de forma manual.

Muchas gracias de ante mano.

**Comment by ecarpintero** [comment]
I'm sorry I forgot to put it in English, many hours working hahaha.

Good.

The generator was not able to produce a level within a given time limit. The reason for that is usually that there is some problem with the configuration of the generator.

I have tried to change the configuration of the Dunegeon Generator.
The doors both in the corridor and the room are 1 in size. The corridor has 2 doors and the room has 4. They are set manually.

Thank you very much in advance.

**Comment by ecarpintero** [comment]
Solved, the Graph was misconfigured

**Comment by OndrejNepozitek** [comment]
I'm glad you solved it!
