### ISSUE TITLE
Fog Of War Implementation : Each polygon must have at least 4 points.

### ISSUE THREAD

**Issue by hugojobe** [OndrejNepozitek/Edgar-Unity#114]
Hi ! 
I followed exactely the tutorial in the documentation but I get this error at runtime :

Can you help me please ?

Thanks :)

```ArgumentException: Each polygon must have at least 4 points.
Edgar.Geometry.PolygonGrid2D.CheckIntegrity()`
Edgar.Geometry.PolygonGrid2D..ctor (System.Collections.Generic.IEnumerable`1[T] points)
Edgar.Unity.Polygon2D.GetGridPolygon () (at Assets/Edgar/Runtime/Common/Utils/Polygon2D.cs:94)
Edgar.Unity.Polygon2D.GetAllPoints () (at Assets/Edgar/Runtime/Common/Utils/Polygon2D.cs:75)
Edgar.Unity.FogOfWarGrid2D.GetPolygonPoints (Edgar.Unity.Polygon2D polygon) (at Assets/Edgar/Runtime/Grid2D/Common/FogOfWar/FogOfWarGrid2D.cs:555)
Edgar.Unity.FogOfWarGrid2D.GetTilesToReveal (System.Collections.Generic.List`1[T] roomsToReveal) (at Assets/Edgar/Runtime/Grid2D/Common/FogOfWar/FogOfWarGrid2D.cs:289)
Edgar.Unity.FogOfWarGrid2D+<RevealRoomCoroutine>d__50.MoveNext () (at Assets/Edgar/Runtime/Grid2D/Common/FogOfWar/FogOfWarGrid2D.cs:430)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Edgar.Unity.FogOfWarGrid2D:RevealRooms(List1, Nullable1, Boolean) (at Assets/Edgar/Runtime/Grid2D/Common/FogOfWar/FogOfWarGrid2D.cs:267)
Edgar.Unity.FogOfWarGrid2D:RevealRoomAndNeighbors(RoomInstanceGrid2D, Nullable`1, Boolean) (at Assets/Edgar/Runtime/Grid2D/Common/FogOfWar/FogOfWarGrid2D.cs:251)
FOGTrigger:OnTriggerEnter2D(Collider2D) (at Assets/Scripts/FOGTrigger.cs:28)```

**Comment by OndrejNepozitek** [comment]
Hello! Are you using the latest version of Edgar? What version of Unity do you have? 

Are you doing something non-standard with the generator? Because the error looks like your room data got somehow corrupted and it's weird that it would happen only after the Fog of War is trying to reveal the room.

How are you running your setup? Is it all while in play mode or are you generating your level inside the editor (without play mode) and then entering the play mode with an already generated level? Because that could at least lead to some weird serialization issue.

Does the error happen right when you generate the level or do you have to do some extra steps?

Does the FogOfWar example that's inside the examples folder work for you?

**Comment by hugojobe** [comment]
I use the latest version, yes and I have Unity 2020.3.
I think I don't do something strange in my rooms, they look like a square or L-shaped
The error happened after I added the FOW component and all it's setup...
I generate my rooms in play mode.
The error happen right after room generation and, I think, before or while FOW generation.

Thanks

**Comment by OndrejNepozitek** [comment]
After the error happens, can you please look at the "Generated Level" game object and there's a field called `Room instances` and in each room instance there's `Outline Polygon` -> `Points`:

![image](https://user-images.githubusercontent.com/2265359/186835860-b72d809c-1d17-4b62-b0b9-464daf893d53.png)

Your error indicates that there's a room instance which doesn't have at least 4 points in the array. Can you please check if you can find such room?

**Comment by hugojobe** [comment]
I'll check this evening sorry, because I'm at work and I don'thave Unity with me :/ 
I'll edit this comment in 8/9 hours

**Comment by hugojobe** [comment]
All my rooms have 4 points or more...

**Comment by OndrejNepozitek** [comment]
Weird. Now I suspect there's a problem inside your FOGTrigger script. Can you please show me the insides of the script? I suspect that there might be some serialization issues or something like that.

Or if you can just zip the whole project (the Assets folder should suffice) and send it to me that could also help. It's always quite hard to do this "remote debugging".

**Comment by hugojobe** [comment]
I'll send you the whole project by email :)

**Comment by OndrejNepozitek** [comment]
I think I found the problem. In your room template prefabs, the `RoomInfo (Grid2D)` component is attached to the root game object of the prefab. This later messes up the actual `RoomInfo (Grid2D)` component that should only be added after a level is generated. In turn, your FOGTrigger script somehow uses an uninitialised `RoomInstance` where the outline polygon is empty.

The solution is to go through your room templates and remove the  `RoomInfo (Grid2D)` component from the root game objects. After that, it should work.

Let me know if this fixes it for you!

**Comment by hugojobe** [comment]
I works thanks !
