### ISSUE TITLE
Is generator deterministic?

### ISSUE THREAD

**Issue by nodoxi** [OndrejNepozitek/Edgar-Unity#123]
I am making cooperative game and want to generate same map on all machines.
How to set seed to be sure that all maps will be indentical

**Comment by OndrejNepozitek** [comment]
Hey, just use the same seed on all the clients and you should get identical results. There's an example in the docs regarding how to configure the seed via a script: https://ondrejnepozitek.github.io/Edgar-Unity/docs/generators/dungeon-generator/#change-the-configuration-from-a-script

Also make sure that whatever you do randomly after the level is generated, you use the same seeded instance on all clients. If you have some logic in a post-processing script, you can access the ".Random" property of that script and use it for seeded randomness. Or you can you any other approach.

Let me know if you have any other question.

**Comment by nodoxi** [comment]
Thank you. that's exactly what I needed
