### ISSUE TITLE
Fog of war reveal part of normal room when revealing a single corridor room

### ISSUE THREAD

**Issue by hippopennyThinh** [OndrejNepozitek/Edgar-Unity#126]
Hello!
Is there a way to make it so that when the player steps into a corridor room, the fog of war reveals that corridor room and part of the room the corridor is leading to?
Currently the corridor has a trigger that will call the FogOfWarGrid2D.Instance.RevealRoom() function, the corridor gets revealed just fine but i also want some tiles of other room to be revealed as well, like when a normal room gets revealed some part of the neighbouring corridors also get revealed

**Comment by OndrejNepozitek** [comment]
Hey, I think I tried that some time ago but it looked kinda weird if I used the same logic that I use to reveal the tiles of the corridors.

**Comment by hippopennyThinh** [comment]
Hello again! Sorry for the late reply
Is there a function or any way of implementation so i can test it out?

**Comment by OndrejNepozitek** [comment]
Hey, I don't have anything implemented right now but I can try to revisit this soon. However, I'm quite busy now, will try to reply next week.

**Comment by hippopennyThinh** [comment]
Thank you, please take your time

**Comment by hippopennyThinh** [comment]
![image](https://github.com/OndrejNepozitek/Edgar-Unity/assets/135583130/aed80beb-c2fe-4e3c-b4c7-c2959ce9ad79)
Hello, sorry for keep bothering you
Is there a way to make it so that the outline of the room (the blue part) has the same effect as the entrance to the corridor (the red part)?
I'm having a bit of problem where some particles get cut off like this and i believe it is due to that
![image](https://github.com/OndrejNepozitek/Edgar-Unity/assets/135583130/f3ce5df3-c23e-42ef-add2-85d95132a5ab)

**Comment by OndrejNepozitek** [comment]
> ![image](https://private-user-images.githubusercontent.com/135583130/305608439-aed80beb-c2fe-4e3c-b4c7-c2959ce9ad79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDUyNTUsIm5iZiI6MTcwODgwNDk1NSwicGF0aCI6Ii8xMzU1ODMxMzAvMzA1NjA4NDM5LWFlZDgwYmViLWMyZmUtNGUzYy1iNGM3LWMyOTU5Y2U5YWQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQyMDAyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Mjc5MGMxZWI2OGE4MTc1NWE5YzM4ZWUzNTA0Njc4Y2MyYzdjMmU1MDBlZjE5MmViOThhZmUzZDc4MmEwNGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TDTAFshwL4U5NKOJMkCSl9dtVXJQZT-aHJRlA7d5O68) Hello, sorry for keep bothering you Is there a way to make it so that the outline of the room (the blue part) has the same effect as the entrance to the corridor (the red part)? I'm having a bit of problem where some particles get cut off like this and i believe it is due to that ![image](https://private-user-images.githubusercontent.com/135583130/305608537-f3ce5df3-c23e-42ef-add2-85d95132a5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDUyNTUsIm5iZiI6MTcwODgwNDk1NSwicGF0aCI6Ii8xMzU1ODMxMzAvMzA1NjA4NTM3LWYzY2U1ZGYzLWMyM2UtNDJlZi1hZGQyLTg1ZDk1MTMyYTVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQyMDAyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDI1ZDQzMDdlMmFhNjU5ODllNDVjZjY0OTk2NDJjNGY3NTQ3Y2YxMTYwYjM5NThmMDMzZWQ3YmE3ZDgyODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VD4OTCxTnyV_ZtEs646IBol6NLOVvLiQaTA45msz7FM)

Hey, if you want to experiment with it, I can make the outline of each room to be extended by 1 extra tile. But what that means is that if there is another room right next to your current room, it will also get revealed, which would look weird. So you must configure the algorithm so that there's at least one empty tile between each pair of rooms. You can do that in the Generator component -> "Minimum room distance". Keep in mind that it might affect the performance of the generator a bit.

If you want to try this out, use this snippet of code starting from line 289 in the FogOfWarGrid2D file, replacing the original content: 

            // Go through the rooms and set the target fog value
            foreach (var room in roomsToReveal)
            {
                var points = GetPolygonPoints(room.OutlinePolygon);
                var extendedOutline = GetExtendedOutline(points);
                
                foreach (var point in points.Concat(extendedOutline))
                {
                    tiles[point] = new TileInfo(revealedFogValue, false);
                }
            }

**Comment by OndrejNepozitek** [comment]
> Hello! Is there a way to make it so that when the player steps into a corridor room, the fog of war reveals that corridor room and part of the room the corridor is leading to? Currently the corridor has a trigger that will call the FogOfWarGrid2D.Instance.RevealRoom() function, the corridor gets revealed just fine but i also want some tiles of other room to be revealed as well, like when a normal room gets revealed some part of the neighbouring corridors also get revealed

I tried to make it work but it would require a bigger effort so I don't think I can make this happen in the near future.
