### ISSUE TITLE
how to save generated map but in game ?

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/Edgar-Unity#33]
for exaample , play the project then click generate map then back to main menu then go to that map agan without generating level but use last generated map

**Comment by longtran2904** [comment]
I think you should save the seed of the generated map because the generated map will be the same if has the same seed.

**Comment by OndrejNepozitek** [comment]
As longtran2904 said, you can generate the same map by storing the seed of the generator and then generating a level with the same seed.

You should be also able to create a prefab from the game object that holds the whole level. However, there were some problems with Unity do properly serializing whether a collider is disabled or enabled, so I don't know whether this approach doesn't come with some weird side effects that I'm not aware of.
