### ISSUE TITLE
Configure which doors can be connected together

### ISSUE THREAD

**Issue by OndrejNepozitek** [OndrejNepozitek/Edgar-Unity#52]
This feature will be included only in the PRO version.

It is currently not possible to choose which doors can be connected together. For example, we could use this with isometric levels to mark the elevation of individual doors. Or we may want to choose that some door positions are reserved only for a specific type of rooms.

This issue needs more information.

**Comment by TechieCrow** [comment]
Would this feature mean you can do something like this but without having to use specific door sizes?

The way i'm doing it is my normal corridors use 2 wide doors while these special corridors need 3 wide to connect on correct rooms
![94341815_2468023983495020_8562412819524354048_n](https://user-images.githubusercontent.com/4921235/80404875-c09c0880-88b9-11ea-83c1-0a2b139736ff.png)

**Comment by OndrejNepozitek** [comment]
Yeah, exactly this. The simplest usecase could be something like creating different "connector" ScriptableObjects like "Basic door", "Secret door" etc., and you would then assign these connectors to individual doors and the algorithm would connect only the doors with the same connector.  And if you needed something more advanced, it would be great if you could be able to provide your own algorithm that would receive a pair of doors from two different room templates and it would decide whether they can be connected together or not.

**Comment by OndrejNepozitek** [comment]
Btw, if you now want to distinguish between two types of doors/corridors but don't want to have different sizes of corridors, you can probably work around it by having a corridor with 2 wide doors but assigning only a 1 wide door position. By doing that, you can trick the algorithm to only connect the correct type of rooms, while still having the same sizes of corridors.

**Comment by TechieCrow** [comment]
Would absolutely love this idea, it will make dungeons so easier to customise and reduce the amount of room prefabs too :) Can't wait for this pro version!

Also that worked great, I didn't think the corridors will match up properly but indeed it seems to :D Thanks!

**Comment by OndrejNepozitek** [comment]
Is included in v2.0.0-alpha.8
