### ISSUE TITLE
Fog of War

### ISSUE THREAD

**Issue by OndrejNepozitek** [OndrejNepozitek/Edgar-Unity#59]
The goal of this feature is to implement a fog of war mechanism that would let users hide and reveal individual rooms in generated levels.

Features:
- reveal/hide rooms
- choose the opacity of the fog, e.g. make rooms that are currently inactive to appear to be slightly in the fog
- choose the colour of the fog
- animate the fog from one opacity to another
- animate the fog based on the distance from a player

Notes:
- to showcase this feature, we must be able to detect when a player enters/leaves a room (e.g. by a collider placed on the floor tilemap layer)
- if implemented using shaders, we must make sure that the solution works both with the built-in render pipeline and with URP/LWRP/HDRP (this thread might be useful - https://forum.unity.com/threads/how-to-know-if-i-have-the-lwrp-hdrp-api-at-compile-time.546513/)

**Comment by pvalium** [comment]
is there any roadmap of this feature?

**Comment by OndrejNepozitek** [comment]
Hey! I've been quite busy recently due to my other responsibilities but I hope to have more time in August to focus on adding new features to this project. I can't promise anything but at least I can give this higher priority if I know that someone would use it.

**Comment by pvalium** [comment]
Thanks guy, u re awesome :)

**Comment by OndrejNepozitek** [comment]
Added in v2.0.0-alpha.6
