### ISSUE TITLE
Dead Cells exemple

### ISSUE THREAD

**Issue by geuks** [OndrejNepozitek/Edgar-Unity#64]
Hi, there is a merge bug in Dead Cells exemple scenes.

![Capture](https://user-images.githubusercontent.com/23451354/82378493-7bd14080-9a25-11ea-93ea-3086598c6744.PNG)

Layers are not set correctly :

![Captur2e](https://user-images.githubusercontent.com/23451354/82378525-85f33f00-9a25-11ea-91d4-61bfe2305f0f.PNG)

**Comment by OndrejNepozitek** [comment]
Hey! Thanks for your report. There's still quite a lot of work that needs to be done with the Dead Cells example.
