### ISSUE TITLE
How to know when it's timeout and restart it through code?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/Edgar-Unity#66]
I want to know when it will timeout through scirpt and then maybe restart the process.

**Comment by OndrejNepozitek** [comment]
Hey! How often does it happen that the generator timeouts? It usually means that the structure of your level graph is too difficult or that there is some problem with your room templates. For example, interconnected cycles are very hard for the algorithm, or maybe you have a small room template and try to connect too many neighbours to it.  If you send me the exported map description ("Export map description" button in the "Advanced" section) together with a screenshot of your level graph, I may be able to help you. The generator is usually quite fast if you do not make the input unnecessarily complex.

If you want to just detect the timeout, the simplest way right now is to wrap the call to the "Generate" method of the generator into a try-catch block. The exception that is thrown when a timeout occurs is the InvalidOperationException (which is probably not the best choice - I should replace that with a custom exception just for the timeout). So you should be able to catch this exception and call the generator again if needed.

**Comment by longtran2904** [comment]
I just simply want to detect the timeout and then restart the process through code. How to restart it (or how to the generated method)?

**Comment by OndrejNepozitek** [comment]
Do you have some sort of game manager that calls the generator through code? Or do you just rely on the "Generate on Start" option of the generator?

**Comment by longtran2904** [comment]
I just use the "Generate on Start" option

**Comment by OndrejNepozitek** [comment]
The "Generate on Start" method is there only for the simplest use-cases. If you want to have more control over the generator, you have to call it manually from code.

Here is a very simple example on how to restart the generator until it successfully generated a level. You just have to add this component to a game object in the scene and disable the "Generate on Start" option.

```
using System;
using ProceduralLevelGenerator.Unity.Generators.DungeonGenerator;
using UnityEngine;

namespace ProceduralLevelGenerator
{
    public class SimpleGameManager : MonoBehaviour
    {
        private void Start()
        {
            // Find the generator (MAKE SURE THAT THE GAME OBJECT NAME IS CORRECT)
            var generator = GameObject.Find("Dungeon Generator").GetComponent<DungeonGenerator>();

            var levelGenerated = false;

            // Loop until a level is successfully generated
            while (!levelGenerated)
            {
                try
                {
                    // Try to generate the level
                    generator.Generate();

                    // If we get here, that means that there was no timeout
                    Debug.Log("Level generated");
                    levelGenerated = true;
                }
                catch (InvalidOperationException)
                {
                    // If we get here, there was a timeout
                    Debug.Log("Timeout encountered");
                }
            }
        }
    }
}
```

P.S.: This code was written against the most recent version of the asset so let me know if you have any problems in case you are using an older version.

**Comment by longtran2904** [comment]
Okay, i've just tested it and it worked. But i'm using an older version so the namespace was a bit different. Are there any easy ways to update the version?

**Comment by OndrejNepozitek** [comment]
It depends on how willing you are to do some manual changes. This asset is still in its alpha stage so there are sometimes breaking changes.

The update process would be something like this:
1. Make sure that you have a backup of your project in case something goes wrong
2. Delete the whole Assets/ProceduralLevelGenerator folder. This step expects that you did not modify the files that are inside this folder because otherwise, you would lose all the changes.
3. Import the newest version of the asset

After this step, I would expect some compile errors because of namespace changes or API changes. I know that you implemented your custom tilemap layers handler.  One namespace was changed in that file. And in CustomRoomTemplateInitializer the class now inherits from "RoomTemplateInitializerBase" instead of "BaseRoomTemplateInitializer" and also a namespace was changed. If you did not customize the generator in any other way, there should be no other changes needed.  (The rotations of tiles are now fixed in the generator itself so you do not need the fix that I discussed with you in a different issue here on Github)

So you have to decide if it makes sense to upgrade. If you decide to upgrade and have any problems, let me know.

**Comment by longtran2904** [comment]
Hey, i've just updated to the current version and been fine so far. Thank you! (Also i know this is not the right place to post this but this is a quick feedback: Sometime i want to disable all the custom post processing tasks for debug purpose but there aren't any easy ways to do that (you have to manually remove and then reassign it after the debug) so i think you should add a usePostProcessing bool to ask whether or not to use the post processing tasks).

**Comment by longtran2904** [comment]
I've just opened my level graph (I made this one before the update) and double click on the graph editor view to create a new room but I received this in the console: 
![image](https://user-images.githubusercontent.com/53656110/87625141-a274d480-c753-11ea-95a6-a50367157654.png)

The 2 error are:

Instance of Assets.ProceduralLevelGenerator.Scripts.Generators.Common.LevelGraph.Room couldn't be created because there is no script with that name.
ArgumentNullException: Value cannot be null.

How to fix this?

**Comment by longtran2904** [comment]
When I double-clicked on the first error it took me to this line:
![image](https://user-images.githubusercontent.com/53656110/87625342-20d17680-c754-11ea-88d1-e71e77c268af.png)

**Comment by OndrejNepozitek** [comment]
Thanks for letting me know. I know where is the problem and provide a new version in a few hours. Unfortunately, these things are really hard to test automatically so it sometimes happens that it breaks.

**Comment by longtran2904** [comment]
So the problem just occurred on the old graph. If I make a new level graph it won't happen. I think maybe because the update process makes some change to the namespace so the old level graph wouldn't be compatible.

**Comment by OndrejNepozitek** [comment]
Yes, it's exactly that - problem with a namespace. I released a hotfix version where it should be fixed.
