### ISSUE TITLE
Do i need to purchase the pro version to add custom fields and color to each room in the graph editor?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/Edgar-Unity#78]
In your Enter the Gungeon example I saw you had the room script to inherited from the RoomBase class. I also found the RoomBase class was in the free version so can I add custom names and colors in the graph editor with the free version?

**Comment by OndrejNepozitek** [comment]
Unfortunately, it is not possible in the free version. Even though there exists the RoomBase class and you can inherit from it, it is not easily possible to use the custom room implementation in your level graphs.
