### ISSUE TITLE
Dungeon generation problem

### ISSUE THREAD

**Issue by learner-yun** [OndrejNepozitek/Edgar-Unity#80]
when I click Generate level button，a errer occurs.
MissingReferenceException: The variable IndividualRoomTemplates of Room doesn't exist anymore.
You probably need to reassign the IndividualRoomTemplates variable of the 'Room' script in the inspector.
I would like to ask if I have done any wrong steps

**Comment by learner-yun** [comment]
It doesn't seem to be able to read the room that I prefabricated in advance

**Comment by OndrejNepozitek** [comment]
Hey!
It seems like you added room templates to some rooms in your level graph and perhaps deleted them later so the reference is now incorrect? Please go through individual rooms in your level graph and check that if you are using custom room templates for that room, that all the room templates are correctly assigned and there are no missing references.
