### ISSUE TITLE
strange behaviour fog

### ISSUE THREAD

**Issue by luisgsoft** [OndrejNepozitek/Edgar-Unity#83]
Hi!
I've configured fog for dungeon and for minimap. Dungeon has fow component and minimap has fow alternative camera script
In editor runs all perfect. Nice job.
In android minimap runs ok, but dungeon is alwais in fog. I can walk and minimap is revealing while main camera is always in fog.
If i put fog of war component in minimap camera, and remove it from main_camera, minimap runs ok too.

So the main problem is with main_camera in android. I have a cinemachine vCam running, i don't know if this can be the problem.

Ah. And fog of war example scene is not running on my unity editor (2020.1.9)

**Comment by OndrejNepozitek** [comment]
So, if I understand you correctly:
- fog works when you enter play mode inside the editor
- fog does not work for the main camera when you build the game for android

Are you using LWRP, URP or the builtin render pipeline?
In which version of Unity editor does it work?

**Comment by pvalium** [comment]
Unity 2020.9
Built in pipeline

**Comment by pvalium** [comment]
2020.1.9*

**Comment by OndrejNepozitek** [comment]
I downloaded Unity 2020.1.13f1 (the latest recommended version) to test the android build on the Minimap/FogOfWar example scenes. And it seems like everything works correctly. The fog is working both for the main camera and for the minimap camera. I used the built-in render pipeline. Moreover, the fog of war example scene works as well for me. 

Can you try disabling the cinemachine vCam? I've got no experience with that so I cannot really try. Unfortunately, if I cannot reproduce your issue, it is very hard to help you.

**Comment by pvalium** [comment]
I think that example scene is not running by my physics matrix.
I'll try to disable cinemachine cam and i'll inform you about results

Thanks

**Comment by pvalium** [comment]
I left you a video:
https://youtu.be/GG_NORN87QU

Here you can see:
1-Initialize fow. Minimap ok, main camera not
2-Reload fow. Nothing happends
3.Disable fow. Main camera runs ok
4.Enable fow. Main camera freezes. Minimap runs ok, and gameplay are running in bakground. I can move player, but camera not refreshes

I've tried to remove cinemachine. Same result.

**Comment by OndrejNepozitek** [comment]
Thanks for the video!

Please try to do the following:
- Open the Assets\Edgar\Runtime\FogOfWar\FogOfWar.shader file
- Try to add `ZTest Always` right bellow line 17, it should look like this:
```
		Pass {
			ZTest Always
			CGPROGRAM
```

I followed this thread - https://forum.unity.com/threads/graphics-blit-not-working-for-android.534835/ - and their issue seems similar to your issue and they said that adding this line helps. I cannot test it myself as my android phone does not have this problem.

Let me know if that helps.

**Comment by pvalium** [comment]
Yes. This solved this issue!

Thank you!

**Comment by OndrejNepozitek** [comment]
Great! I'll include that in the next release/hotfix.

By the way, how is the performance of the fog of war on mobiles? Is it okay?

**Comment by pvalium** [comment]
Well, performance is improvable. Without fow, i get around 50 fps. With fow, I get around 30fps. With this performance, i'll use it only in minimap

My mobile is Xiaomi miA2 lite updated to last android version

**Comment by OndrejNepozitek** [comment]
I've got one potential performance improvement in mind. If I manage to make it work, I'll get back to you.

**Comment by pvalium** [comment]
Perfect. Thanks a lot

**Comment by OndrejNepozitek** [comment]
I've sent you an email with 2 modified scripts - FogOfWar.cs and FogOfWarAdditionalCamera.cs. Please put these files in the _Assets\Edgar\Runtime\FogOfWar_ folder and overwrite the old files.

Instead of the OnRenderImage hook, I now use OnPreRender and OnPostRender which should improve the performance mainly on mobile devices. On my PC, the FPS improved from circa 800 to circa 1100.

Let me know if that helps!

**Comment by pvalium** [comment]
Performance si similar, Maybe around 5 fps more.
In my mobile and game, cost of enable fog in main camera is around 15-20 fps loss
