### ISSUE TITLE
Are the RoomInstance.Doors sorted in order? How to use RoomInstance.Position?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/Edgar-Unity#85]
Are the RoomInstance.Doors sorted in some order like clockwise or are they random? I have a corridor, how to check which door is connected to the left or right?
How to use RoomInstance.Position? Should I add it with the position of the GameObject Rooms?

**Comment by OndrejNepozitek** [comment]
Hey!
The Doors are in no particular order.

Internally, I use the following code to set the position of room templates:
```
roomTemplateInstance.transform.position = position;
```
where the position is equal to the RoomInstace.Position.

Do you have any specific goals in mind? I can probably give you some more information if I know what you're trying to achieve.

**Comment by longtran2904** [comment]
I had an instance of a corridor that connected to 2 rooms. How to know which RoomInstance.Doors of the corridor are connected to the left and which are connected to the right.

**Comment by OndrejNepozitek** [comment]
You can use `DoorInstance.FacingDirection` to do that. If there's a room connected on the left side of the door, its facing direction should be equal to Vector2Int.up. And the same holds for all the other directions.

**Comment by longtran2904** [comment]
Wait, I thought it should be Vector2Int.Left.

**Comment by OndrejNepozitek** [comment]
Yeah, you're right. It seems like I was reading a comment in the documentation which said "Up" and forgot that we're talking about a room facing to the left.
