### ISSUE TITLE
Different grids

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/Edgar-Unity#86]
Is there any way to have 2 grids with several sizes inside a room?
For ex, I have a Tilemap with floor, and grid size is 1,1,1(128px), but I want a tilemap floor2, which is a second layer with decorations, and this tiles are size 0.25 (32px)

**Comment by OndrejNepozitek** [comment]
Unfortunately, that is currently not possible. I don't even know how I would implement something like that. I expect that if I retrieve tiles from multiple tilemaps but in the same position, I will get tiles that are displayed in the same position on the screen. If there were multiple grids, none of that would work.

If you have any idea on how could that be implemented, let me know.

**Comment by pvalium** [comment]
Ok, I'll search other solution
Thank you
