### ISSUE TITLE
Bug when you want to create a positioning door - v2.0.0-alpha.6

### ISSUE THREAD

**Issue by CaribeAtomic** [OndrejNepozitek/Edgar-Unity#90]
I try to create a new door for a room with the **add door position** method but the door only appears in the middle of the canvas and is not selected to apply it to the desired position.

This only happens in the v2.0.0-alpha.6  with Unity 2020.1

Version v2.0.0-alpha.5 doesn't have this problem.

**Comment by OndrejNepozitek** [comment]
If I understand correctly, you want to add a door position using the manual mode, you click the "Add door positions" button in the inspector, click on the screen at the position you want to add the door and the door appears in the center of the screen instead? Can you please show me a screenshot/video of the wrong behavior?

**Comment by CaribeAtomic** [comment]
I found my problem which is not an Asset error. Well ...,   While I was trying to create the video capture of the error I realized that my project in unity is created as a 3d project, so it had the option 2d mode disabled of the unity that makes it impossible to position a door since the axes are like **xyz**, and not **XY** like your Dead Cell example works.

I do not know if I explained well.

I'm so embarrassed. You can now close this thread.

**Comment by OndrejNepozitek** [comment]
That's okay! Let me know if you have any other problems.
