### ISSUE TITLE
"Disable Custom Post Processing Tasks" Missing check in Platformer Generator

### ISSUE THREAD

**Issue by Lyntier** [OndrejNepozitek/Edgar-Unity#98]
`DungeonGeneratorBase.cs` checks if post processing is disabled with this code:

```cs
var customPostProcessTasks = !DisableCustomPostProcessing
        ? CustomPostProcessTasks
        : new List<DungeonGeneratorPostProcessBase>();
return new PostProcessTask(PostProcessConfig, () => new DungeonTilemapLayersHandler(), customPostProcessTasks);
```

`DungeonGenerator.cs` doesn't override this method, so it works fine. However, in the pro version, `PlatformerGenerator.cs` overrides this method and does not add the post processing check back in, making the Platformer Generator always execute post processing tasks.

Using the code above in that method in the Platformer Generator works.

**Comment by OndrejNepozitek** [comment]
Thanks for the report! I was just in the process of releasing a small hotfix so I'll include this in it.
